In [1]:
import pandas as pd
import polars as pl
import duckdb
import matplotlib.pyplot as plt
import plotly.express as px

data_frame1 = pd.read_csv("data/sales.csv")
data_frame2 = pd.read_csv("data/sales_update.csv")
# Buat tabel permanen dari DataFrame dengan alias "sales"
duckdb.sql("CREATE TABLE sales AS SELECT * FROM data_frame1")
duckdb.sql("CREATE TABLE sales_update AS SELECT * FROM data_frame2")

In [3]:
duckdb.sql("""
    INSERT INTO sales_update (tanggal, produk, kategori, jumlah, pendapatan)
    VALUES (DATE '2023-01-07', 'Kerah', 'Atasan', 3, 450000)
""")

In [4]:
duckdb.sql("COPY sales_update TO 'data/sales_update.csv' (HEADER, DELIMITER ',')")

In [5]:
duckdb.sql("DESCRIBE sales_update")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ tanggal     │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ produk      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ kategori    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ jumlah      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ pendapatan  │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [13]:
duckdb.sql("""
    SELECT *
    FROM sales_update
    WHERE produk = 'Kaos'
""").df()

     tanggal produk kategori  jumlah  pendapatan
0 2023-01-01   Kaos   Atasan      10      500000
1 2023-01-05   Kaos   Atasan       6      300000

In [16]:
duckdb.sql("""
    SELECT *
    FROM sales_update
    WHERE (produk = 'Kaos' OR kategori = 'Bawahan')
""").df()

     tanggal  produk kategori  jumlah  pendapatan
0 2023-01-01    Kaos   Atasan      10      500000
1 2023-01-05    Kaos   Atasan       6      300000
2 2023-01-02  Celana  Bawahan       5      750000
3 2023-01-04     Rok  Bawahan       3      450000
4 2023-01-05  Celana  Bawahan       2      200000
5 2023-01-07     Rok  Bawahan       3      450000